#include "chunkserializer.h"
#include <cstring>

const char* ChunkSerializer::GetChunkName(uint32_t chunkId) {
	switch (chunkId) {
		case W3D_CHUNK_MESH: return "W3D_CHUNK_MESH";
		case W3D_CHUNK_VERTICES: return "W3D_CHUNK_VERTICES";
		case W3D_CHUNK_VERTEX_NORMALS: return "W3D_CHUNK_VERTEX_NORMALS";
		case W3D_CHUNK_MESH_USER_TEXT: return "W3D_CHUNK_MESH_USER_TEXT";
		case W3D_CHUNK_VERTEX_INFLUENCES: return "W3D_CHUNK_VERTEX_INFLUENCES";
		case W3D_CHUNK_MESH_HEADER3: return "W3D_CHUNK_MESH_HEADER3";
		case W3D_CHUNK_TRIANGLES: return "W3D_CHUNK_TRIANGLES";
		case W3D_CHUNK_VERTEX_SHADE_INDICES: return "W3D_CHUNK_VERTEX_SHADE_INDICES";
		case W3D_CHUNK_PRELIT_UNLIT: return "W3D_CHUNK_PRELIT_UNLIT";
		case W3D_CHUNK_PRELIT_VERTEX: return "W3D_CHUNK_PRELIT_VERTEX";
		case W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS: return "W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS";
		case W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE: return "W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE";
		case W3D_CHUNK_MATERIAL_INFO: return "W3D_CHUNK_MATERIAL_INFO";
		case W3D_CHUNK_SHADERS: return "W3D_CHUNK_SHADERS";
		case W3D_CHUNK_VERTEX_MATERIALS: return "W3D_CHUNK_VERTEX_MATERIALS";
		case W3D_CHUNK_VERTEX_MATERIAL: return "W3D_CHUNK_VERTEX_MATERIAL";
		case W3D_CHUNK_VERTEX_MATERIAL_NAME: return "W3D_CHUNK_VERTEX_MATERIAL_NAME";
		case W3D_CHUNK_VERTEX_MATERIAL_INFO: return "W3D_CHUNK_VERTEX_MATERIAL_INFO";
		case W3D_CHUNK_VERTEX_MAPPER_ARGS0: return "W3D_CHUNK_VERTEX_MAPPER_ARGS0";
		case W3D_CHUNK_VERTEX_MAPPER_ARGS1: return "W3D_CHUNK_VERTEX_MAPPER_ARGS1";
		case W3D_CHUNK_TEXTURES: return "W3D_CHUNK_TEXTURES";
		case W3D_CHUNK_TEXTURE: return "W3D_CHUNK_TEXTURE";
		case W3D_CHUNK_TEXTURE_NAME: return "W3D_CHUNK_TEXTURE_NAME";
		case W3D_CHUNK_TEXTURE_INFO: return "W3D_CHUNK_TEXTURE_INFO";
		case W3D_CHUNK_MATERIAL_PASS: return "W3D_CHUNK_MATERIAL_PASS";
		case W3D_CHUNK_VERTEX_MATERIAL_IDS: return "W3D_CHUNK_VERTEX_MATERIAL_IDS";
		case W3D_CHUNK_SHADER_IDS: return "W3D_CHUNK_SHADER_IDS";
		case W3D_CHUNK_DCG: return "W3D_CHUNK_DCG";
		case W3D_CHUNK_DIG: return "W3D_CHUNK_DIG";
		case W3D_CHUNK_SCG: return "W3D_CHUNK_SCG";
		case W3D_CHUNK_TEXTURE_STAGE: return "W3D_CHUNK_TEXTURE_STAGE";
		case W3D_CHUNK_TEXTURE_IDS: return "W3D_CHUNK_TEXTURE_IDS";
		case W3D_CHUNK_STAGE_TEXCOORDS: return "W3D_CHUNK_STAGE_TEXCOORDS";
		case W3D_CHUNK_PER_FACE_TEXCOORD_IDS: return "W3D_CHUNK_PER_FACE_TEXCOORD_IDS";
		case W3D_CHUNK_DEFORM: return "W3D_CHUNK_DEFORM";
		case W3D_CHUNK_DEFORM_SET: return "W3D_CHUNK_DEFORM_SET";
		case W3D_CHUNK_DEFORM_KEYFRAME: return "W3D_CHUNK_DEFORM_KEYFRAME";
		case W3D_CHUNK_DEFORM_DATA: return "W3D_CHUNK_DEFORM_DATA";
		case W3D_CHUNK_PS2_SHADERS: return "W3D_CHUNK_PS2_SHADERS";
		case W3D_CHUNK_AABTREE: return "W3D_CHUNK_AABTREE";
		case W3D_CHUNK_AABTREE_HEADER: return "W3D_CHUNK_AABTREE_HEADER";
		case W3D_CHUNK_AABTREE_POLYINDICES: return "W3D_CHUNK_AABTREE_POLYINDICES";
		case W3D_CHUNK_AABTREE_NODES: return "W3D_CHUNK_AABTREE_NODES";
		case W3D_CHUNK_HIERARCHY: return "W3D_CHUNK_HIERARCHY";
		case W3D_CHUNK_HIERARCHY_HEADER: return "W3D_CHUNK_HIERARCHY_HEADER";
		case W3D_CHUNK_PIVOTS: return "W3D_CHUNK_PIVOTS";
		case W3D_CHUNK_PIVOT_FIXUPS: return "W3D_CHUNK_PIVOT_FIXUPS";
		case W3D_CHUNK_ANIMATION: return "W3D_CHUNK_ANIMATION";
		case W3D_CHUNK_ANIMATION_HEADER: return "W3D_CHUNK_ANIMATION_HEADER";
		case W3D_CHUNK_ANIMATION_CHANNEL: return "W3D_CHUNK_ANIMATION_CHANNEL";
		case W3D_CHUNK_BIT_CHANNEL: return "W3D_CHUNK_BIT_CHANNEL";
		case W3D_CHUNK_COMPRESSED_ANIMATION: return "W3D_CHUNK_COMPRESSED_ANIMATION";
		case W3D_CHUNK_COMPRESSED_ANIMATION_HEADER: return "W3D_CHUNK_COMPRESSED_ANIMATION_HEADER";
		case W3D_CHUNK_COMPRESSED_ANIMATION_CHANNEL: return "W3D_CHUNK_COMPRESSED_ANIMATION_CHANNEL";
		case W3D_CHUNK_COMPRESSED_BIT_CHANNEL: return "W3D_CHUNK_COMPRESSED_BIT_CHANNEL";
		case W3D_CHUNK_MORPH_ANIMATION: return "W3D_CHUNK_MORPH_ANIMATION";
		case W3D_CHUNK_MORPHANIM_HEADER: return "W3D_CHUNK_MORPHANIM_HEADER";
		case W3D_CHUNK_MORPHANIM_CHANNEL: return "W3D_CHUNK_MORPHANIM_CHANNEL";
		case W3D_CHUNK_MORPHANIM_POSENAME: return "W3D_CHUNK_MORPHANIM_POSENAME";
		case W3D_CHUNK_MORPHANIM_KEYDATA: return "W3D_CHUNK_MORPHANIM_KEYDATA";
		case W3D_CHUNK_MORPHANIM_PIVOTCHANNELDATA: return "W3D_CHUNK_MORPHANIM_PIVOTCHANNELDATA";
		case W3D_CHUNK_HMODEL: return "W3D_CHUNK_HMODEL";
		case W3D_CHUNK_HMODEL_HEADER: return "W3D_CHUNK_HMODEL_HEADER";
		case W3D_CHUNK_NODE: return "W3D_CHUNK_NODE";
		case W3D_CHUNK_COLLISION_NODE: return "W3D_CHUNK_COLLISION_NODE";
		case W3D_CHUNK_SKIN_NODE: return "W3D_CHUNK_SKIN_NODE";
		case W3D_CHUNK_LODMODEL: return "W3D_CHUNK_LODMODEL";
		case W3D_CHUNK_LODMODEL_HEADER: return "W3D_CHUNK_LODMODEL_HEADER";
		case W3D_CHUNK_LOD: return "W3D_CHUNK_LOD";
		case W3D_CHUNK_COLLECTION: return "W3D_CHUNK_COLLECTION";
		case W3D_CHUNK_COLLECTION_HEADER: return "W3D_CHUNK_COLLECTION_HEADER";
		case W3D_CHUNK_COLLECTION_OBJ_NAME: return "W3D_CHUNK_COLLECTION_OBJ_NAME";
		case W3D_CHUNK_PLACEHOLDER: return "W3D_CHUNK_PLACEHOLDER";
		case W3D_CHUNK_TRANSFORM_NODE: return "W3D_CHUNK_TRANSFORM_NODE";
		case W3D_CHUNK_POINTS: return "W3D_CHUNK_POINTS";
		case W3D_CHUNK_LIGHT: return "W3D_CHUNK_LIGHT";
		case W3D_CHUNK_LIGHT_INFO: return "W3D_CHUNK_LIGHT_INFO";
		case W3D_CHUNK_SPOT_LIGHT_INFO: return "W3D_CHUNK_SPOT_LIGHT_INFO";
		case W3D_CHUNK_NEAR_ATTENUATION: return "W3D_CHUNK_NEAR_ATTENUATION";
		case W3D_CHUNK_FAR_ATTENUATION: return "W3D_CHUNK_FAR_ATTENUATION";
		case W3D_CHUNK_EMITTER: return "W3D_CHUNK_EMITTER";
		case W3D_CHUNK_EMITTER_HEADER: return "W3D_CHUNK_EMITTER_HEADER";
		case W3D_CHUNK_EMITTER_USER_DATA: return "W3D_CHUNK_EMITTER_USER_DATA";
		case W3D_CHUNK_EMITTER_INFO: return "W3D_CHUNK_EMITTER_INFO";
		case W3D_CHUNK_EMITTER_INFOV2: return "W3D_CHUNK_EMITTER_INFOV2";
		case W3D_CHUNK_EMITTER_PROPS: return "W3D_CHUNK_EMITTER_PROPS";
		case W3D_CHUNK_EMITTER_LINE_PROPERTIES: return "W3D_CHUNK_EMITTER_LINE_PROPERTIES";
		case W3D_CHUNK_EMITTER_ROTATION_KEYFRAMES: return "W3D_CHUNK_EMITTER_ROTATION_KEYFRAMES";
		case W3D_CHUNK_EMITTER_FRAME_KEYFRAMES: return "W3D_CHUNK_EMITTER_FRAME_KEYFRAMES";
		case W3D_CHUNK_EMITTER_BLUR_TIME_KEYFRAMES: return "W3D_CHUNK_EMITTER_BLUR_TIME_KEYFRAMES";
		case W3D_CHUNK_AGGREGATE: return "W3D_CHUNK_AGGREGATE";
		case W3D_CHUNK_AGGREGATE_HEADER: return "W3D_CHUNK_AGGREGATE_HEADER";
		case W3D_CHUNK_AGGREGATE_INFO: return "W3D_CHUNK_AGGREGATE_INFO";
		case W3D_CHUNK_TEXTURE_REPLACER_INFO: return "W3D_CHUNK_TEXTURE_REPLACER_INFO";
		case W3D_CHUNK_AGGREGATE_CLASS_INFO: return "W3D_CHUNK_AGGREGATE_CLASS_INFO";
		case W3D_CHUNK_HLOD: return "W3D_CHUNK_HLOD";
		case W3D_CHUNK_HLOD_HEADER: return "W3D_CHUNK_HLOD_HEADER";
		case W3D_CHUNK_HLOD_LOD_ARRAY: return "W3D_CHUNK_HLOD_LOD_ARRAY";
		case W3D_CHUNK_HLOD_SUB_OBJECT_ARRAY_HEADER: return "W3D_CHUNK_HLOD_SUB_OBJECT_ARRAY_HEADER";
		case W3D_CHUNK_HLOD_SUB_OBJECT: return "W3D_CHUNK_HLOD_SUB_OBJECT";
		case W3D_CHUNK_HLOD_AGGREGATE_ARRAY: return "W3D_CHUNK_HLOD_AGGREGATE_ARRAY";
		case W3D_CHUNK_HLOD_PROXY_ARRAY: return "W3D_CHUNK_HLOD_PROXY_ARRAY";
		case W3D_CHUNK_BOX: return "W3D_CHUNK_BOX";
		case W3D_CHUNK_SPHERE: return "W3D_CHUNK_SPHERE";
		case W3D_CHUNK_RING: return "W3D_CHUNK_RING";
		case W3D_CHUNK_NULL_OBJECT: return "W3D_CHUNK_NULL_OBJECT";
		case W3D_CHUNK_LIGHTSCAPE: return "W3D_CHUNK_LIGHTSCAPE";
		case W3D_CHUNK_LIGHTSCAPE_LIGHT: return "W3D_CHUNK_LIGHTSCAPE_LIGHT";
		case W3D_CHUNK_LIGHT_TRANSFORM: return "W3D_CHUNK_LIGHT_TRANSFORM";
		case W3D_CHUNK_DAZZLE: return "W3D_CHUNK_DAZZLE";
		case W3D_CHUNK_DAZZLE_NAME: return "W3D_CHUNK_DAZZLE_NAME";
		case W3D_CHUNK_DAZZLE_TYPENAME: return "W3D_CHUNK_DAZZLE_TYPENAME";
		default: return "W3D_CHUNK_UNKNOWN";
	}
}

bool ChunkSerializer::HasSubChunks(uint32_t chunkId) {
	switch (chunkId) {
		case W3D_CHUNK_MESH:
		case W3D_CHUNK_PRELIT_UNLIT:
		case W3D_CHUNK_PRELIT_VERTEX:
		case W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS:
		case W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE:
		case W3D_CHUNK_VERTEX_MATERIALS:
		case W3D_CHUNK_VERTEX_MATERIAL:
		case W3D_CHUNK_TEXTURES:
		case W3D_CHUNK_TEXTURE:
		case W3D_CHUNK_MATERIAL_PASS:
		case W3D_CHUNK_TEXTURE_STAGE:
		case W3D_CHUNK_FX_SHADERS:
		case W3D_CHUNK_FX_SHADER:
		case W3D_CHUNK_DEFORM:
		case W3D_CHUNK_DEFORM_SET:
		case W3D_CHUNK_DEFORM_KEYFRAME:
		case W3D_CHUNK_AABTREE:
		case W3D_CHUNK_HIERARCHY:
		case W3D_CHUNK_ANIMATION:
		case W3D_CHUNK_COMPRESSED_ANIMATION:
		case W3D_CHUNK_MORPH_ANIMATION:
		case W3D_CHUNK_MORPHANIM_CHANNEL:
		case W3D_CHUNK_HMODEL:
		case W3D_CHUNK_LODMODEL:
		case W3D_CHUNK_COLLECTION:
		case W3D_CHUNK_LIGHT:
		case W3D_CHUNK_EMITTER:
		case W3D_CHUNK_AGGREGATE:
		case W3D_CHUNK_HLOD:
		case W3D_CHUNK_HLOD_LOD_ARRAY:
		case W3D_CHUNK_LIGHTSCAPE:
		case W3D_CHUNK_DAZZLE:
			return true;
		default:
			return false;
	}
}

std::unique_ptr<ChunkData> ChunkSerializer::ReadChunk(ChunkLoadClass& cload) {
	uint32_t chunkId = cload.Cur_Chunk_ID();
	uint32_t chunkSize = cload.Cur_Chunk_Length();
	const char* chunkName = GetChunkName(chunkId);
	
	auto chunk = std::make_unique<ChunkData>(chunkId, chunkSize, chunkName);
	
	if (HasSubChunks(chunkId) || cload.Contains_Chunks()) {
		while (cload.Open_Chunk()) {
			auto subChunk = ReadChunk(cload);
			if (subChunk) {
				chunk->subChunks.push_back(std::move(subChunk));
			}
			cload.Close_Chunk();
		}
	} else {
		ReadChunkData(cload, *chunk);
	}
	
	return chunk;
}

void ChunkSerializer::ReadChunkData(ChunkLoadClass& cload, ChunkData& chunk) {
	uint32_t size = cload.Cur_Chunk_Length();
	if (size > 0) {
		chunk.rawData.resize(size);
		cload.Read(chunk.rawData.data(), size);
		
		if (chunk.rawData.back() == 0) {
			chunk.dataType = ChunkDataType::STRING;
		} else {
			chunk.dataType = ChunkDataType::ARRAY;
		}
	}
}

bool ChunkSerializer::WriteChunk(ChunkSaveClass& csave, const ChunkData& chunk) {
	if (!csave.Begin_Chunk(chunk.chunkId)) {
		return false;
	}
	
	if (!chunk.subChunks.empty()) {
		for (const auto& subChunk : chunk.subChunks) {
			if (!WriteChunk(csave, *subChunk)) {
				return false;
			}
		}
	} else if (!chunk.rawData.empty()) {
		csave.Write(chunk.rawData.data(), chunk.rawData.size());
	}
	
	return csave.End_Chunk();
}

