#pragma once

enum {
	BUFFER_TYPE_DX8,
	BUFFER_TYPE_SORTING,
	BUFFER_TYPE_DYNAMIC_DX8,
	BUFFER_TYPE_DYNAMIC_SORTING,
	BUFFER_TYPE_INVALID
};

constexpr unsigned BUFFER_TYPE_STATIC = BUFFER_TYPE_DX8;
constexpr unsigned BUFFER_TYPE_DYNAMIC = BUFFER_TYPE_DYNAMIC_DX8;
